# Homework Assignement 4 - SVM exercises
Beatriz Gamboa Pereira - 201705220

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy as sp
from sklearn.datasets import load_iris
import sklearn.model_selection as skm
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 

In [10]:
# loading attributes and classes of the iris dataset
X, y = load_iris(return_X_y= True)

1. Apply SVM classifier to the full, 3 classes, iris data set. Use a 20% holdout to obtain the confusion matrix for a linear kernel.


In [11]:
# split dataset in train and test
xTrain, xTest, yTrain, yTest = skm.train_test_split(X, y, random_state = 27, train_size = 0.8)

# chosing SVC model and applying to the training set 
Mod = SVC(kernel='linear')
Mod.fit(xTrain, yTrain)
# finding y predicted
yPred = Mod.predict(xTest)

confusionMatrix = confusion_matrix(yTest, yPred)
print(confusionMatrix)

[[ 7  0  0]
 [ 0 11  0]
 [ 0  0 12]]


2. Try different values for the cost C from 1E-10 to 2. What do you observe?

In [12]:
costs = np.linspace(1e-10,2,10)

for cost in costs:
    mod = SVC(kernel='linear', C=cost)
    mod.fit(xTrain, yTrain)
    
    yPred = mod.predict(xTest)
    
    confMat = confusion_matrix(yTest, yPred)
    
    print('Cost: ', round(cost,2))
    print('Accuracy score: ', round(accuracy_score(yTest, yPred),2))
    print(confMat, '\n')

Cost:  0.0
Accuracy score:  0.23
[[ 7  0  0]
 [11  0  0]
 [12  0  0]] 

Cost:  0.22
Accuracy score:  0.97
[[ 7  0  0]
 [ 0 10  1]
 [ 0  0 12]] 

Cost:  0.44
Accuracy score:  1.0
[[ 7  0  0]
 [ 0 11  0]
 [ 0  0 12]] 

Cost:  0.67
Accuracy score:  0.97
[[ 7  0  0]
 [ 0 11  0]
 [ 0  1 11]] 

Cost:  0.89
Accuracy score:  1.0
[[ 7  0  0]
 [ 0 11  0]
 [ 0  0 12]] 

Cost:  1.11
Accuracy score:  0.97
[[ 7  0  0]
 [ 0 11  0]
 [ 0  1 11]] 

Cost:  1.33
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  1.56
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  1.78
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  2.0
Accuracy score:  0.97
[[ 7  0  0]
 [ 0 11  0]
 [ 0  1 11]] 



For the chosen seed, we can't really see the dependency of the accuracy of the model with the different costs, but, in general we get good results except for the first cost of 1e-10.

3. Try using other kernels.

In [13]:
def testKernelCost(Costs,Kern):
    print('Costs: ',Costs)
    print(Kern, ' kernel\n\n')

    for cost in Costs:
        MOD = SVC(kernel=Kern, C=cost)
        MOD.fit(xTrain, yTrain)

        yPred = MOD.predict(xTest)

        confMat = confusion_matrix(yTest, yPred)

        print('Cost: ', round(cost,2))
        print('Accuracy score: ', round(accuracy_score(yTest, yPred),2))
        print(confMat, '\n')

In [14]:
testKernelCost(costs,'rbf')

Costs:  [1.00000000e-10 2.22222222e-01 4.44444445e-01 6.66666667e-01
 8.88888889e-01 1.11111111e+00 1.33333333e+00 1.55555556e+00
 1.77777778e+00 2.00000000e+00]
rbf  kernel


Cost:  0.0
Accuracy score:  0.23
[[ 7  0  0]
 [11  0  0]
 [12  0  0]] 

Cost:  0.22
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  0.44
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  0.67
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  0.89
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  1.11
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  1.33
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  1.56
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  1.78
Accuracy score:  0.97
[[ 7  0  0]
 [ 0 10  1]
 [ 0  0 12]] 

Cost:  2.0
Accuracy score:  0.97
[[ 7  0  0]
 [ 0 10  1]
 [ 0  0 12]] 



In [15]:
testKernelCost(costs,'poly')

Costs:  [1.00000000e-10 2.22222222e-01 4.44444445e-01 6.66666667e-01
 8.88888889e-01 1.11111111e+00 1.33333333e+00 1.55555556e+00
 1.77777778e+00 2.00000000e+00]
poly  kernel


Cost:  0.0
Accuracy score:  0.23
[[ 7  0  0]
 [11  0  0]
 [12  0  0]] 

Cost:  0.22
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  0.44
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  0.67
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  0.89
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  1.11
Accuracy score:  0.9
[[ 7  0  0]
 [ 0 10  1]
 [ 0  2 10]] 

Cost:  1.33
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  1.56
Accuracy score:  0.93
[[ 7  0  0]
 [ 0 10  1]
 [ 0  1 11]] 

Cost:  1.78
Accuracy score:  0.9
[[ 7  0  0]
 [ 0 10  1]
 [ 0  2 10]] 

Cost:  2.0
Accuracy score:  0.9
[[ 7  0  0]
 [ 0 10  1]
 [ 0  2 10]] 



Again, for the chosen seed, we see that we get relatively good results in general, except for the first 1e-10 cost. We notice that poly gives slightly worse results than linear and rbf.

4. Formulate at least 2 hypotheses regarding this classification problem and the hyperparameters kernel and C. For example: the X kernel is better than the Y kernel when C=Y; given a kernel, using a value of C of X is the same as using Y.

**Hypothesis 1:** For the two costs of $C=1$ and $C=1.78$, and the same kernel - linear, $C=1.78$ gives better results. $\to$ $H_{0} : $ $C=1$ and $C=1.78$ both give the same results for the same kernel - linear

**Hypothesis 2:** For the two kernels poly and rbf and the same cost $C=1.78$, poly gives better results. $\to$ $H_{0} : $ poly and rbf give the same results for the same cost $C=1.78$.

5. Check your hypotheses using 10 fold corss validation and t-test. Don't forget to shuffle.

In [16]:
X, y = load_iris(return_X_y = True)
shuffled = skm.ShuffleSplit(n_splits=10, random_state = 27)

# Hypothesis 1 - samme kernel different costs

m1 = SVC(kernel = 'poly', C=1)
score1 = skm.cross_val_score(m1, X, y, cv=shuffled)

m2 = SVC(kernel = 'poly', C=1.78)
score2 = skm.cross_val_score(m2, X, y, cv=shuffled)

relativeH1 = sp.stats.ttest_rel(score1,score2)

print('Hypothesis 1: ', relativeH1)


# Hypothesis 2 - samme cost different kernels

mPoly = SVC(kernel = 'poly', C=1.78)
scorePoly = skm.cross_val_score(mPoly, X, y, cv=shuffled)

mRBF = SVC(kernel = 'rbf', C=1.78)
scoreRBF = skm.cross_val_score(mRBF, X, y, cv=shuffled)

relativeH2 = sp.stats.ttest_rel(scorePoly,scoreRBF)

print('Hypothesis 2: ', relativeH2)

Hypothesis 1:  Ttest_relResult(statistic=-0.42857142857142855, pvalue=0.6783097418055798)
Hypothesis 2:  Ttest_relResult(statistic=0.5570860145311556, pvalue=0.5910512317836047)


For both tests, we see that pvalue is greater than $\alpha=0.05$, so both our hypothesis are rejected, which means that $H_0$ is accepted in both cases. Conclusion, for the given seed, our results are similar if we vary kernel and cost independently. This could be further tested if we changed seeds, for example.